categories:
  clinical_study:
    keywords:
      - clinical
      - patient
      - caregiver
      - care
      - intervention
      - treatment
      - therapy
      - rehabilitation
  
  neuroscience:
    keywords:
      - hippocampal
      - prefrontal
      - neural
      - brain
      - neuron
      - synaptic
      - cortex
      - amygdala
  
  biomarker:
    keywords:
      - biomarker
      - blood marker
      - csf marker
      - plasma marker
      - protein
      - tau
      - amyloid
      - neurofilament
  
  ai_ml:
    keywords:
      - machine learning
      - deep learning
      - artificial intelligence
      - neural network
      - algorithm
      - prediction
  
  imaging:
    keywords:
      - MRI
      - magnetic resonance imaging
      - structural MRI
      - functional MRI
      - neuroimaging
      - imaging
      - scan
  
  cognitive_assessment:
    keywords:
      - cognitive
      - memory
      - assessment
      - test
      - evaluation
      - screening
      - diagnosis
      - large scale
      - population study
      - cohort study
