baseURL: 'https://clair8853.github.io/'
languageCode: 'ko-kr'
defaultContentLanguage: 'ko'
title: 'CLAIR 공부방'
theme: 'PaperMod'

params:
  env: production
  description: "MCI 논문 자동 수집 및 분석 블로그"
  author: CLAIR
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  
  homeInfoParams:
    Title: "MCI Papers Archive"
    Content: "매일 업데이트되는 MCI 관련 논문 모음"

  socialIcons:
    - name: "github"
      url: "https://github.com/clair8853"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON
