name: Deploy Hugo Blog

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'  # 매일 07:00 JST (UTC+9)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Update Blog Content
        run: |
          python main.py --daily
          mkdir -p blog/content/posts/
          cp output/trend_report_*.md blog/content/posts/
          cp output/category_trends_*.png blog/static/images/

      - name: Build
        working-directory: ./blog
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: ./blog/public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
