name: Deploy Hugo Blog

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'  # 매일 JST 07:00 (UTC 22:00)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Blog Content
        env:
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          PUBMED_EMAIL: ${{ secrets.PUBMED_EMAIL }}
        run: |
          python main.py --daily
          mkdir -p blog/content/posts/
          mkdir -p blog/static/images/
          cp output/trend_report_*.md blog/content/posts/ || echo "No trend reports to copy"
          cp output/*_*.png blog/static/images/ || echo "No images to copy"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        working-directory: ./blog
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: ./blog/public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
